fig, ax = plt.subplots(figsize=[30,9])
plt.plot(df_daily_steps_mba['steps'], label = 'steps')
plt.plot(df_daily_steps_mba['7_day_avg'], label = '7-day rolling average', lw = 3)
plt.plot(df_daily_steps_mba['30_day_avg'], label = '30-day rolling average', lw = 3)
plt.plot(df_daily_steps_mba['365_day_avg'], label = '365-day rolling average', lw = 3)
fig.set_facecolor('white')
plt.grid()
plt.legend()
plt.xticks(rotation=45)
plt.title('Daily step count during MBA and rolling averages')
plt.savefig('graphs\\daily_steps_during_MBA.png',dpi=400)